### ISSUE TITLE
Make seamark layer and coordinate grid permanent

### ISSUE THREAD

**Issue by malcolmh** [OpenNauticalChart/online_map#19]
If this is a nautical chart then seamarks and lat/lon grid should always be present. It is an added complication for the user if these layers need to be selected.

**Comment by OlafHannemann** [comment]
@malcolmh I would like to keep them selectable like it is in the moment. If you load the map for the first time they are selected by default, hence both layers are visible. Tested with Firefox, Google Chrome and Opera. This should be no extra complication to the user.
In some cases mostly in inland navigation views there are that much items displayed, that I would like to turn the seamark layer out for a short time, just to see the shore line or something like this.

Another issue is the the menu may be overloaded later on and will be confusing to user. In this case we need to redesign the menus to make them clearer. I think there is no action needed at the moment.

**Comment by Dirk--** [comment]
I agree with Olaf: Users should make these decisions
